### PR TITLE
Update toastWidth in toastElemt.js

### PR DESCRIPTION
**Pull request by ywroh**
It is the best used library among various react toasts open sources.

Currently, I am making a website with nextjs, but if the mobileS size is the same as iphone5, the toast width is 360, so it will not appear on the screen.

Therefore, I modified the toastwidth to 300. Thank you.

### CODE REVIEW

**Comment by jossmac** [comment]
@ywroh you can target the toast element with the class name `react-toast-notifications__toast` and style it however you like

**Comment by ywroh** [comment]
Thank you. I have checked the way you informed me. But I solved it using customToast as below.

`
const MyCustomToast = ({ children, ...props }) => (
  <DefaultToast style={{ width: '300px' }} {...props}>
    <div>{children}</div>
  </DefaultToast>
);
`

`<ToastProvider components={{ Toast: MyCustomToast }}>`

**Comment by ywroh** [comment]
Thank you. I have checked the way you informed me. But I solved it using customToast as below.

`const MyCustomToast = ({ children, ...props }) => (
  <DefaultToast style={{ width: '300px' }} {...props}>
    <div>{children}</div>
  </DefaultToast>
);`

`<ToastProvider components={{ Toast: MyCustomToast }}>`

**Comment by jossmac** [comment]
Perfect, that works too @ywroh!

Just FYI `children` don't need to be extracted from `props` unless you're doing more than just passing them on. So you could do something like:

```jsx
const MyCustomToast = props => <DefaultToast style={{ width: 300 }} {...props} />;
```

**Comment by ywroh** [comment]
@jossmac I learned well thanks to your advice. Thank you in advance. Have a nice day!

**Pull request closed without merging**
