### PR TITLE
Pass props through DefaultToast

### PR DESCRIPTION
**Pull request by elijahcarrel**
In one of my projects, I'd like the ability to take `DefaultToast` and use it essentially as is but modify it in the slightest way (in particular, I'd like to add styles to it). `ToastElement` already passes extra props down to the inner div, so all that's needed is for `DefaultToast` to pass extra props to `ToastElement`.

Let me know your thoughts!

### CODE REVIEW

**Comment by jossmac** [comment]
LGTM, thanks @elijahcarrel!

**Comment by elijahcarrel** [comment]
Thanks @jossmac! Any chance you could push a new release with this? 🙏

**Comment by jossmac** [comment]
That's up in `2.2.5`, sorry for the slow release.

**Comment by elijahcarrel** [comment]
No worries, thanks so much!

**Pull request merged**
