### PR TITLE
Optimize webpack build.

### PR DESCRIPTION
**Pull request by fc**
Refer to #15

### CODE REVIEW

**Comment by fc** [comment]
Ahh.. whoops, hold off on merging this.  It looks like it breaks autoDismiss but not sure why.

**Comment by fc** [comment]
bwawhaha, it was a typo, never mind. All is good.

**Comment by fc** [comment]
@jossmac ?

**Comment by Carlows** [comment]
I'm wondering, what makes this library being so heavy?

**Comment by fc** [comment]
@Carlows there is babelification... but no minification.

**Comment by jossmac** [comment]
Closing in favour of #33

Not keen on UMD build

**Pull request closed without merging**
