### PR TITLE
Support React Hooks

### PR DESCRIPTION
**Pull request by Toanzzz**
Related Issue #20

### CODE REVIEW

**Comment by nagey** [comment]
👍 Looking forward to this hitting the main package!

**Comment by Jaikant** [comment]
👍 Thanks, it would be awesome if this could be included into the main package.

**Comment by darewreck54** [comment]
@jossmac Anyway we can get this PR reviewed and merged?

**Comment by IsTheJack** [comment]
I created a temporary solution until this package supports react hooks. Solution: Component wrapping:

**Example using Typescript**
```tsx
import * as React from 'react'
import { ToastProvider, withToastManager } from 'react-toast-notifications'

const CustomToastContext = React.createContext<ToastManager>({
  add: (content: string, options?: Options) => () => undefined,
  remove: (id: Id) => () => undefined,
  toasts: [],
})
const { Provider } = CustomToastContext

const RawToastProvider: React.FC<{ toastManager: ToastManager }> = ({ toastManager, children }) => {
  return <Provider value={toastManager}>{children}</Provider>
}

const WithManagerToastConfig = withToastManager(RawToastProvider)

const CustomToastProvider: React.FC<{}> = ({ children }) => (
  <ToastProvider
    autoDismissTimeout={6000}
    placement="bottom-left"
  >
    <WithManagerToastConfig>{children}</WithManagerToastConfig>
  </ToastProvider>
)

export const useToasts = () => React.useContext(CustomToastContext)

export default CustomToastProvider

// Types
export interface ToastManager {
  add: AddFn
  remove: RemoveFn
  toasts: ToastsType
}

type Id = string
interface Options {
  appearance?: 'error' | 'info' | 'success',
  autoDismiss?: boolean,
}
type Callback = ((id: Id) => void)

type AddFn = (content: string, options?: Options) => Callback
type RemoveFn = (id: Id) => Callback

export type Placement =
  | 'bottom-left'
  | 'bottom-center'
  | 'bottom-right'
  | 'top-left'
  | 'top-center'
  | 'top-right'

type ToastType = Options & { content: string, id: Id }
type ToastsType = ToastType[]

```

**Comment by jossmac** [comment]
@Toanzzz thanks for this. I tried to resolve the conflicts, but couldn't manage it without rebase/force push. Your stuff made it into #42 with a slight change to the hook API:

```jsx
const { addToast, removeToast, toasts } = useToasts
```

I thought `add` and `remove` were too generic to be comfortably deconstructed.

That's available now `@2.0.0`, sorry for the delay folks.

**Pull request closed without merging**
